// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IHashProvider is an autogenerated mock type for the IHashProvider type
type IHashProvider struct {
	mock.Mock
}

type mockConstructorTestingTNewIHashProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewIHashProvider creates a new instance of IHashProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIHashProvider(t mockConstructorTestingTNewIHashProvider) *IHashProvider {
	mock := &IHashProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
