// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	types "github.com/J-Obog/tasket/src/types"
	mock "github.com/stretchr/testify/mock"
)

// ILogManager is an autogenerated mock type for the ILogManager type
type ILogManager struct {
	mock.Mock
}

// CreateLog provides a mock function with given fields: taskId, logReq
func (_m *ILogManager) CreateLog(taskId string, logReq types.NewLog) {
	_m.Called(taskId, logReq)
}

// GetLogsByFilter provides a mock function with given fields: taskId, filter
func (_m *ILogManager) GetLogsByFilter(taskId string, filter types.LogOptions) ([]types.Log, error) {
	ret := _m.Called(taskId, filter)

	var r0 []types.Log
	if rf, ok := ret.Get(0).(func(string, types.LogOptions) []types.Log); ok {
		r0 = rf(taskId, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Log)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, types.LogOptions) error); ok {
		r1 = rf(taskId, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLogsByTask provides a mock function with given fields: taskId
func (_m *ILogManager) GetLogsByTask(taskId string) ([]types.Log, error) {
	ret := _m.Called(taskId)

	var r0 []types.Log
	if rf, ok := ret.Get(0).(func(string) []types.Log); ok {
		r0 = rf(taskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Log)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewILogManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewILogManager creates a new instance of ILogManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewILogManager(t mockConstructorTestingTNewILogManager) *ILogManager {
	mock := &ILogManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
