// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	rest "github.com/J-Obog/tasket/src/rest"
)

// ITaskResource is an autogenerated mock type for the ITaskResource type
type ITaskResource struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: req
func (_m *ITaskResource) CreateTask(req rest.RestRequest) (rest.RestResponse, int) {
	ret := _m.Called(req)

	var r0 rest.RestResponse
	if rf, ok := ret.Get(0).(func(rest.RestRequest) rest.RestResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(rest.RestResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(rest.RestRequest) int); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetTask provides a mock function with given fields: req
func (_m *ITaskResource) GetTask(req rest.RestRequest) (rest.RestResponse, int) {
	ret := _m.Called(req)

	var r0 rest.RestResponse
	if rf, ok := ret.Get(0).(func(rest.RestRequest) rest.RestResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(rest.RestResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(rest.RestRequest) int); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetTaskLogs provides a mock function with given fields: req
func (_m *ITaskResource) GetTaskLogs(req rest.RestRequest) (rest.RestResponse, int) {
	ret := _m.Called(req)

	var r0 rest.RestResponse
	if rf, ok := ret.Get(0).(func(rest.RestRequest) rest.RestResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(rest.RestResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(rest.RestRequest) int); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetTasks provides a mock function with given fields: req
func (_m *ITaskResource) GetTasks(req rest.RestRequest) (rest.RestResponse, int) {
	ret := _m.Called(req)

	var r0 rest.RestResponse
	if rf, ok := ret.Get(0).(func(rest.RestRequest) rest.RestResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(rest.RestResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(rest.RestRequest) int); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// StopTask provides a mock function with given fields: req
func (_m *ITaskResource) StopTask(req rest.RestRequest) (rest.RestResponse, int) {
	ret := _m.Called(req)

	var r0 rest.RestResponse
	if rf, ok := ret.Get(0).(func(rest.RestRequest) rest.RestResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(rest.RestResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(rest.RestRequest) int); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: req
func (_m *ITaskResource) UpdateTask(req rest.RestRequest) (rest.RestResponse, int) {
	ret := _m.Called(req)

	var r0 rest.RestResponse
	if rf, ok := ret.Get(0).(func(rest.RestRequest) rest.RestResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(rest.RestResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(rest.RestRequest) int); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

type mockConstructorTestingTNewITaskResource interface {
	mock.TestingT
	Cleanup(func())
}

// NewITaskResource creates a new instance of ITaskResource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewITaskResource(t mockConstructorTestingTNewITaskResource) *ITaskResource {
	mock := &ITaskResource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
