// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	rest "github.com/J-Obog/tasket/src/rest"
)

// IUserResource is an autogenerated mock type for the IUserResource type
type IUserResource struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: req
func (_m *IUserResource) CreateUser(req rest.RestRequest) (rest.RestResponse, int) {
	ret := _m.Called(req)

	var r0 rest.RestResponse
	if rf, ok := ret.Get(0).(func(rest.RestRequest) rest.RestResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(rest.RestResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(rest.RestRequest) int); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: req
func (_m *IUserResource) DeleteUser(req rest.RestRequest) (rest.RestResponse, int) {
	ret := _m.Called(req)

	var r0 rest.RestResponse
	if rf, ok := ret.Get(0).(func(rest.RestRequest) rest.RestResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(rest.RestResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(rest.RestRequest) int); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: req
func (_m *IUserResource) GetUser(req rest.RestRequest) (rest.RestResponse, int) {
	ret := _m.Called(req)

	var r0 rest.RestResponse
	if rf, ok := ret.Get(0).(func(rest.RestRequest) rest.RestResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(rest.RestResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(rest.RestRequest) int); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

type mockConstructorTestingTNewIUserResource interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUserResource creates a new instance of IUserResource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUserResource(t mockConstructorTestingTNewIUserResource) *IUserResource {
	mock := &IUserResource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
