// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IUUIDProvider is an autogenerated mock type for the IUUIDProvider type
type IUUIDProvider struct {
	mock.Mock
}

// UUID provides a mock function with given fields:
func (_m *IUUIDProvider) UUID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewIUUIDProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUUIDProvider creates a new instance of IUUIDProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUUIDProvider(t mockConstructorTestingTNewIUUIDProvider) *IUUIDProvider {
	mock := &IUUIDProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
