// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: message
func (_m *Logger) Debug(message string) {
	_m.Called(message)
}

// Error provides a mock function with given fields: message
func (_m *Logger) Error(message string) {
	_m.Called(message)
}

// Info provides a mock function with given fields: message
func (_m *Logger) Info(message string) {
	_m.Called(message)
}

// Warn provides a mock function with given fields: message
func (_m *Logger) Warn(message string) {
	_m.Called(message)
}

type mockConstructorTestingTNewLogger interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogger(t mockConstructorTestingTNewLogger) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
