// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	model "github.com/J-Obog/tasket/src/model"
	mock "github.com/stretchr/testify/mock"
)

// LogStore is an autogenerated mock type for the LogStore type
type LogStore struct {
	mock.Mock
}

// GetBy provides a mock function with given fields: taskId, options
func (_m *LogStore) GetBy(taskId string, options model.LogOptions) ([]model.Log, error) {
	ret := _m.Called(taskId, options)

	var r0 []model.Log
	if rf, ok := ret.Get(0).(func(string, model.LogOptions) []model.Log); ok {
		r0 = rf(taskId, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Log)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, model.LogOptions) error); ok {
		r1 = rf(taskId, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: log
func (_m *LogStore) Insert(log model.Log) error {
	ret := _m.Called(log)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Log) error); ok {
		r0 = rf(log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewLogStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogStore creates a new instance of LogStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogStore(t mockConstructorTestingTNewLogStore) *LogStore {
	mock := &LogStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
